# Assignment Day 3

In [9]:
import numpy as np
import pandas as pd
array = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))
new_array = 2 * array


In [10]:

print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(new_array)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


# creating the dictionary

In [ ]:
dictionary = {'A': 1, 'B': 2, 'C': 5}

In [19]:
dictionary = {
	"product_name": ["laptop", "mobile", "tablet"],
	"product_price": [60000, 20000, 15000],
	"stock_quantiy": [30, 50, 70]
}
df = pd.DataFrame(dictionary)
print(df)

  product_name  product_price  stock_quantiy
0       laptop          60000             30
1       mobile          20000             50
2       tablet          15000             70


In [22]:
# Check if 'stock quantiy' in dictionary is greater than 50
datafiltered = df[df['stock_quantiy'] > 50]
print(datafiltered)

  product_name  product_price  stock_quantiy
2       tablet          15000             70
